$ANSIBLE_VAULT;1.1;AES256
37316630646630363361346636323965326662323432653762303937353262303830613266623033
6235366538613431353835643737643030313834373137350a336661306165336337356533346163
35653665646430363339353066306637643838393437623732306434393335373762343463323436
6362643131356437380a343836323662643931316163343734656163313635613836666233653963
63343262643434643935313665633136346336653936333833346432346636373163666430313639
65373862666561613764303434333439633230333736653961643238633534626666346363393133
32393864663734623764383264653265623838323639333265386438346537633464366330633235
62373066646362366638393433653063306366383536656534306134356362623365343834636239
33346234386134313966383534303030396562383039623334613637613330316534386433313662
39313632323930383932373861363933366261343633333262666331343031613664363430376365
37313332396130633861623964376536323739353161666332623164343266333662313031643833
30623936336535633735303239656262333661393864623937663833333934326337353137306333
61653434623034623330303039323235343436363763653532666436383031633430386463353433
65663036356138333930613164373831623634323530643730386136316334613532386162643838
303862333432396234393564306233626361
