$ANSIBLE_VAULT;1.1;AES256
39346566393061323365356230626335656464363831656532343135346339333765353835393939
6662343139373432616630653539663133396364666136620a636331656463663132633936393132
36636263666137316239316530366365343839376463346164353236653831333236353735393131
3930333931643633340a663639646461633433333234363739626164656634616532333461653161
31653962373139656535633561653263666434383266346239333636653139643731326363383862
3232333535323361373464636564353432656664393131393633
