---
# WorkshopItems (Steam Workshop ID List)
zomboid_workshop_ids:
  - "2800337234"
  - "2809595776"
  - "2640569820"
  - "522891356"
  - "2313387159"
  - "2536865912"
  - "2978007916"
  - "3067798182"
  - "2763647806"
  - "2286124931"
  - "2875848298"
  - "3129327862"
  - "2787291513"
  - "3039365081"
  - "3134776712"
  - "2337452747"
  - "2599752664"
  - "2529746725"
  - "2950902979"
  - "3028261329"
  - "1516836158"
  - "2806456685"
  - "2463499011"
  - "2706119869"
  - "2852309899"
  - "3173649443"
  - "2694448564"
  - "2945221351"
  - "3204323366"
  - "3180893708"
  - "2725216703"
  - "2169435993"
  - "2685168362"
  - "2789097802"
  - "2706673644"
  - "3115293671"
  - "2847184718"
  - "2657661246"
  - "2196102849"
  - "2901962885"
  - "2903771337"
  - "2142622992"
  - "2921029369"
  - "2686624983"
  - "2725378876"
  - "3075358477"
  - "2769706949"
  - "2487022075"
  - "2392709985"
  - "2744797858"
  - "2987772693"
  - "3342110208"
  - "3040632900"
  - "2946221823"
  - "3072057419"
  - "2384329562"
  - "3009084198"
  - "3030870358"
  - "2900444089"
  - "2867431511"
  - "2818577583"


# Mods (Internal Mod ID List)
# 공백/특수문자 포함 ID는 따옴표("") 사용 필수
zomboid_mod_ids:
# [1. Mod Manager]
  - "ModManager"
  - "ModManagerELO"
  - "ModeManagerAutoSorting"
  - "ModManagerLoadOrderSorter"
  - "ModManagerServer"
  - "modoptions"
  - "ModTemplate"
  - "EasyConfigChucked"

  # [2. Map Tiles]
  - "Diederiks Tile Palooza"
  - "DylansTiles"
  - "tkTiles_01"

  # [3. Maps]
  - "Trelai_4x4_Steam"
  - "BedfordFalls"
  - "Blackwood"
  - "FORTREDSTONE"
  - "Fort Rock Ridge"
  - "Grapeseed"
  - "Muldraugh Fire Department"
  - "muldraughmilitarybase"
  - "RavenCreek"
  - "WolfExtractionQuest"

  # [4. QoL & Mechanics]
  - "BLTRandomZombies"
  - "blkt_invtrack"
  - "AutoCook"
  - "BetterSortCC"
  - "BB_BreakingIn"
  - "BuildingMenu"
  - "MoreCLR_desc4mood"
  - "CombatText"
  - "BB_CommonSense"
  - "ContainerTooltips"
  - "CraftHelperContinued"
  - "BB_DaysGone_Counter"
  - "DescriptiveSkillTooltips"
  - "EQUIPMENT_UI"
  - "BB_FirstAidOverhaul"
  - "HeadwearWontFall"
  - "qdx_item_condition"
  - "P4MedicalMeister"
  - "MoreDescriptionForTraits4166"
  - "No Mo Culling"
  - "ProximityInventory"
  - "RainWash"
  - "REORDER_CONTAINERS"
  - "REORDER_THE_HOTBAR"
  - "RepairAnyClothes"
  - "RepairAnyMod"
  - "Skizots Visible Boxes and Garbage2"
  - "SleepWithFriends"
  - "simpleStatus"
  - "TheyKnew"
  - "They Knew Fix SpawnChance"
  - "P4TidyUpMeister"
  - "TMC_TrueActions"
  - "tsarslib"
  - "P4VideoMeister"
  - "WorldMapNameSymbols"
  - "NestedContainer01"

  # [5. Translation]
  - "WolfExtractionQuest_KO_TRANSLATE"
  - "BravenPack_KO_TRANSLATE"
  - "PZGKO_Main"
  - "Hx_KR_Mod"
  - "MapNameHangle"
  - "Hx_KR_ClearDescriptionForMoodles"
  - "Hx_KR_Map"

# Map (Folder Name List)
# 순서: [모드 맵] -> [바닐라 맵] -> Muldraugh, KY (필수, 맨 뒤)
zomboid_maps:
  - "Trelai_4x4"
  - "BedfordFalls"
  - "North"
  - "South"
  - "West"
  - "RavenCreek"
  - "Blackwood"
  - "FortRedstone"
  - "Fort Rock Ridge"
  - "Grapeseed"
  - "Muldraugh Fire Department"
  - "Muldraugh Military Base"
  - "Muldraugh, KY"